//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StegoRevealer.UI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LozalizationData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LozalizationData() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StegoRevealer.UI.Resources.Localization.LozalizationData", typeof(LozalizationData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Методы стегоанализа.
        /// </summary>
        public static string AnalyzerTab_MethodsExpander {
            get {
                return ResourceManager.GetString("AnalyzerTab.MethodsExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Встраивание согласно методике комплексного стегоанализа.
        /// </summary>
        public static string AnalyzerTab_Results_ComplexMethodTitle {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.ComplexMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать результаты.
        /// </summary>
        public static string AnalyzerTab_Results_CopyResults {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.CopyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценка заполненности по методу Хи-квадрат.
        /// </summary>
        public static string AnalyzerTab_Results_CsaMethodTitle {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.CsaMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценка заполненности по методу FAN (HCF-COM).
        /// </summary>
        public static string AnalyzerTab_Results_FanMethodEstimation {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.FanMethodEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Встраивание по методу анализа FAN (HCF-COM).
        /// </summary>
        public static string AnalyzerTab_Results_FanMethodTitle {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.FanMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на обнаружено.
        /// </summary>
        public static string AnalyzerTab_Results_HidingDetected {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.HidingDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не обнаружено.
        /// </summary>
        public static string AnalyzerTab_Results_HidingNotDetected {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.HidingNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Совместный вывод.
        /// </summary>
        public static string AnalyzerTab_Results_JointDecisionTitle {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.JointDecisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество бит скрытой информации.
        /// </summary>
        public static string AnalyzerTab_Results_KzchaMethod_BitsNum {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.KzchaMethod.BitsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коэффициенты предполагаемого встраивания.
        /// </summary>
        public static string AnalyzerTab_Results_KzchaMethod_Coeffs {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.KzchaMethod.Coeffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Извлечённая информация.
        /// </summary>
        public static string AnalyzerTab_Results_KzchaMethod_ExtractedData {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.KzchaMethod.ExtractedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружен подозрительный интервал при стегоанализе Коха-Жао.
        /// </summary>
        public static string AnalyzerTab_Results_KzchaMethod_FoundInterval {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.KzchaMethod.FoundInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индексы блоков подозрительного интервала.
        /// </summary>
        public static string AnalyzerTab_Results_KzchaMethod_Indexes {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.KzchaMethod.Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предполагаемый порог встраивания.
        /// </summary>
        public static string AnalyzerTab_Results_KzchaMethod_Threshold {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.KzchaMethod.Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет данных.
        /// </summary>
        public static string AnalyzerTab_Results_NoData {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нет данных.
        /// </summary>
        public static string AnalyzerTab_Results_NoDataLower {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.NoDataLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует.
        /// </summary>
        public static string AnalyzerTab_Results_NoHiding {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.NoHiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отсутствует.
        /// </summary>
        public static string AnalyzerTab_Results_NoHidingLower {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.NoHidingLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анализ не проводился.
        /// </summary>
        public static string AnalyzerTab_Results_NotAnalyzedResult {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.NotAnalyzedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на анализ не проводился.
        /// </summary>
        public static string AnalyzerTab_Results_NotAnalyzedResultLower {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.NotAnalyzedResultLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценка заполненности по методу RS.
        /// </summary>
        public static string AnalyzerTab_Results_RsMethodTitle {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.RsMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценка заполненности по методу SPA.
        /// </summary>
        public static string AnalyzerTab_Results_SpaMethodTitle {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.SpaMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на невозможно определить.
        /// </summary>
        public static string AnalyzerTab_Results_UndefinedResult {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.UndefinedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Встраивание по методу анализа сжатия по Жилкину.
        /// </summary>
        public static string AnalyzerTab_Results_ZcaMethodTitle {
            get {
                return ResourceManager.GetString("AnalyzerTab.Results.ZcaMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты стегоанализа.
        /// </summary>
        public static string AnalyzerTab_ResultsExpander {
            get {
                return ResourceManager.GetString("AnalyzerTab.ResultsExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используемые методы.
        /// </summary>
        public static string AnalyzerTab_UsingMethods {
            get {
                return ResourceManager.GetString("AnalyzerTab.UsingMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес HTTP.
        /// </summary>
        public static string ApiLauncherTab_Config_HttpAddress {
            get {
                return ResourceManager.GetString("ApiLauncherTab.Config.HttpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес HTTPS.
        /// </summary>
        public static string ApiLauncherTab_Config_HttpsAddress {
            get {
                return ResourceManager.GetString("ApiLauncherTab.Config.HttpsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать перенаправление на HTTPS.
        /// </summary>
        public static string ApiLauncherTab_Config_HttpsRedirection {
            get {
                return ResourceManager.GetString("ApiLauncherTab.Config.HttpsRedirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация API.
        /// </summary>
        public static string ApiLauncherTab_Config_Title {
            get {
                return ResourceManager.GetString("ApiLauncherTab.Config.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить API.
        /// </summary>
        public static string ApiLauncherTab_LaunchBtn_Start {
            get {
                return ResourceManager.GetString("ApiLauncherTab.LaunchBtn.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить API.
        /// </summary>
        public static string ApiLauncherTab_LaunchBtn_Stop {
            get {
                return ResourceManager.GetString("ApiLauncherTab.LaunchBtn.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор изображения.
        /// </summary>
        public static string Common_ChooseImage {
            get {
                return ResourceManager.GetString("Common.ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение со встраиванием.
        /// </summary>
        public static string Common_CoveredImageTitle {
            get {
                return ResourceManager.GetString("Common.CoveredImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Затрачено времени.
        /// </summary>
        public static string Common_ElapseTime {
            get {
                return ResourceManager.GetString("Common.ElapseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота.
        /// </summary>
        public static string Common_Image_Height {
            get {
                return ResourceManager.GetString("Common.Image.Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина.
        /// </summary>
        public static string Common_Image_Width {
            get {
                return ResourceManager.GetString("Common.Image.Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение не выбрано.
        /// </summary>
        public static string Common_ImageNotSelected {
            get {
                return ResourceManager.GetString("Common.ImageNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загруженное изображение.
        /// </summary>
        public static string Common_LoadedImageTitle {
            get {
                return ResourceManager.GetString("Common.LoadedImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мс.
        /// </summary>
        public static string Common_Ms {
            get {
                return ResourceManager.GetString("Common.Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нет.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выкл.
        /// </summary>
        public static string Common_Off {
            get {
                return ResourceManager.GetString("Common.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкл.
        /// </summary>
        public static string Common_On {
            get {
                return ResourceManager.GetString("Common.On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть в редакторе.
        /// </summary>
        public static string Common_OpenInEditor {
            get {
                return ResourceManager.GetString("Common.OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры.
        /// </summary>
        public static string Common_Params {
            get {
                return ResourceManager.GetString("Common.Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить в файл.
        /// </summary>
        public static string Common_SaveToFile {
            get {
                return ResourceManager.GetString("Common.SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск.
        /// </summary>
        public static string Common_Start {
            get {
                return ResourceManager.GetString("Common.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на произошла ошибка.
        /// </summary>
        public static string Common_WasError {
            get {
                return ResourceManager.GetString("Common.WasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на да.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индексы блоков.
        /// </summary>
        public static string ExtractorTab_BlocksIndexes {
            get {
                return ResourceManager.GetString("ExtractorTab.BlocksIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина (байт).
        /// </summary>
        public static string ExtractorTab_ByteLength {
            get {
                return ResourceManager.GetString("ExtractorTab.ByteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонстрируемый выше текст отфильтрован: исключены управляющие и заменяющие символы.
        /// </summary>
        public static string ExtractorTab_ExtractedDataDisclaimer {
            get {
                return ResourceManager.GetString("ExtractorTab.ExtractedDataDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необработанные извлечённые данные.
        /// </summary>
        public static string ExtractorTab_ExtractedDataTitle {
            get {
                return ResourceManager.GetString("ExtractorTab.ExtractedDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры извлечения.
        /// </summary>
        public static string ExtractorTab_ExtractionParams {
            get {
                return ResourceManager.GetString("ExtractorTab.ExtractionParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Способ и параметры извлечения.
        /// </summary>
        public static string ExtractorTab_ExtractionParamsAndMethod {
            get {
                return ResourceManager.GetString("ExtractorTab.ExtractionParamsAndMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последовательно.
        /// </summary>
        public static string ExtractorTab_HidingLinear {
            get {
                return ResourceManager.GetString("ExtractorTab.HidingLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Псевдослучайно.
        /// </summary>
        public static string ExtractorTab_HidingRandom {
            get {
                return ResourceManager.GetString("ExtractorTab.HidingRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрытое по Коха-Жао.
        /// </summary>
        public static string ExtractorTab_KzhaHided {
            get {
                return ResourceManager.GetString("ExtractorTab.KzhaHided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрытое в НЗБ.
        /// </summary>
        public static string ExtractorTab_LsbHided {
            get {
                return ResourceManager.GetString("ExtractorTab.LsbHided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры извлечения.
        /// </summary>
        public static string ExtractorTab_ParametersExpander {
            get {
                return ResourceManager.GetString("ExtractorTab.ParametersExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ ГПСЧ.
        /// </summary>
        public static string ExtractorTab_RandomKey {
            get {
                return ResourceManager.GetString("ExtractorTab.RandomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты извлечения.
        /// </summary>
        public static string ExtractorTab_ResultsExpander {
            get {
                return ResourceManager.GetString("ExtractorTab.ResultsExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стартовый индекс.
        /// </summary>
        public static string ExtractorTab_StartIndex {
            get {
                return ResourceManager.GetString("ExtractorTab.StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порог.
        /// </summary>
        public static string ExtractorTab_Threshold {
            get {
                return ResourceManager.GetString("ExtractorTab.Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать файл данных.
        /// </summary>
        public static string HiderTab_ChooseData {
            get {
                return ResourceManager.GetString("HiderTab.ChooseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор скрываемых данных.
        /// </summary>
        public static string HiderTab_ChooseDataTitle {
            get {
                return ResourceManager.GetString("HiderTab.ChooseDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последовательно.
        /// </summary>
        public static string HiderTab_HideLinear {
            get {
                return ResourceManager.GetString("HiderTab.HideLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Псевдослучайно.
        /// </summary>
        public static string HiderTab_HideRandom {
            get {
                return ResourceManager.GetString("HiderTab.HideRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры встраивания.
        /// </summary>
        public static string HiderTab_HiderParams {
            get {
                return ResourceManager.GetString("HiderTab.HiderParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Способ и параметры встраивания.
        /// </summary>
        public static string HiderTab_HiderParamsAndMethod {
            get {
                return ResourceManager.GetString("HiderTab.HiderParamsAndMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение со встраиванием отображено на левой панели.
        /// </summary>
        public static string HiderTab_ImageInLeftPanelInfo {
            get {
                return ResourceManager.GetString("HiderTab.ImageInLeftPanelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод Коха-Жао.
        /// </summary>
        public static string HiderTab_MethodKochZhao {
            get {
                return ResourceManager.GetString("HiderTab.MethodKochZhao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод НЗБ.
        /// </summary>
        public static string HiderTab_MethodLsb {
            get {
                return ResourceManager.GetString("HiderTab.MethodLsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ ГПСЧ.
        /// </summary>
        public static string HiderTab_RandomKey {
            get {
                return ResourceManager.GetString("HiderTab.RandomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить выбор файла данных.
        /// </summary>
        public static string HiderTab_RemoveLoadedData {
            get {
                return ResourceManager.GetString("HiderTab.RemoveLoadedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение со встраиванием.
        /// </summary>
        public static string HiderTab_Results_CoveredImageName {
            get {
                return ResourceManager.GetString("HiderTab.Results.CoveredImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты встраивания.
        /// </summary>
        public static string HiderTab_ResultsExpander {
            get {
                return ResourceManager.GetString("HiderTab.ResultsExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить сформированное изображение со встраиванием.
        /// </summary>
        public static string HiderTab_SaveCoveredImage {
            get {
                return ResourceManager.GetString("HiderTab.SaveCoveredImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стартовый индекс.
        /// </summary>
        public static string HiderTab_StartIndex {
            get {
                return ResourceManager.GetString("HiderTab.StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порог.
        /// </summary>
        public static string HiderTab_Threshold {
            get {
                return ResourceManager.GetString("HiderTab.Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на             Stego Revealer - программный комплекс, предназначенный для осуществления стегоанализа и работы со стеганографическими методами скрытия и извлечения информации.
        ///            
        ///            Доступные методы стегоанализа:
        ///                - методика комплексного стегоанализа;
        ///                - метод оценки по критерию Хи-Квадрат (Chi-Square Attack, CSA);
        ///                - метод Regular-Singular (RS);
        ///                - метод Sample Pair Analysis (SPA);
        ///                - метод Fast Additive Noise  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string InfoTab_AboutText {
            get {
                return ResourceManager.GetString("InfoTab.AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на оценка по CSA.
        /// </summary>
        public static string JointAnalysis_CsaEstimation {
            get {
                return ResourceManager.GetString("JointAnalysis.CsaEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор О.1: Скрытое сообщение не обнаружено, контейнер пуст.
        /// </summary>
        public static string JointAnalysis_Decisions_O1 {
            get {
                return ResourceManager.GetString("JointAnalysis.Decisions.O1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор О.2: Сообщение занимает около {0:0}%, встраивание псевдослучайное.
        /// </summary>
        public static string JointAnalysis_Decisions_O2 {
            get {
                return ResourceManager.GetString("JointAnalysis.Decisions.O2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор О.3: Сообщение занимает около {0:0}%, встраивание последовательное.
        /// </summary>
        public static string JointAnalysis_Decisions_O3 {
            get {
                return ResourceManager.GetString("JointAnalysis.Decisions.O3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор О.4: Сообщение занимает около {0:0}%, встраивание псевдослучайное.
        /// </summary>
        public static string JointAnalysis_Decisions_O4 {
            get {
                return ResourceManager.GetString("JointAnalysis.Decisions.O4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор О.5: Сообщение занимает не менее 80%, встраивание псевдослучайное.
        /// </summary>
        public static string JointAnalysis_Decisions_O5 {
            get {
                return ResourceManager.GetString("JointAnalysis.Decisions.O5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор О.6: Сообщение занимает около 100%, встраивание последовательное.
        /// </summary>
        public static string JointAnalysis_Decisions_O6 {
            get {
                return ResourceManager.GetString("JointAnalysis.Decisions.O6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор О.7: Сообщение занимает около 100%, встраивание псевдослучайное.
        /// </summary>
        public static string JointAnalysis_Decisions_O7 {
            get {
                return ResourceManager.GetString("JointAnalysis.Decisions.O7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Однозначного вывода сделать нельзя, точка не попадает ни в один из секторов.
        /// </summary>
        public static string JointAnalysis_Decisions_Undefined {
            get {
                return ResourceManager.GetString("JointAnalysis.Decisions.Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пустой контейнер.
        /// </summary>
        public static string JointAnalysis_EmptyContainer {
            get {
                return ResourceManager.GetString("JointAnalysis.EmptyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на последовательное встраивание.
        /// </summary>
        public static string JointAnalysis_LinearHiding {
            get {
                return ResourceManager.GetString("JointAnalysis.LinearHiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор O.1.
        /// </summary>
        public static string JointAnalysis_O1SectorTitle {
            get {
                return ResourceManager.GetString("JointAnalysis.O1SectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на псевдослучайное встраивание.
        /// </summary>
        public static string JointAnalysis_RandomHiding {
            get {
                return ResourceManager.GetString("JointAnalysis.RandomHiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат методики формирования вывода при совместном применении методов CSA и RS.
        /// </summary>
        public static string JointAnalysis_ResultTitle {
            get {
                return ResourceManager.GetString("JointAnalysis.ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на оценка по RS.
        /// </summary>
        public static string JointAnalysis_RsEstimation {
            get {
                return ResourceManager.GetString("JointAnalysis.RsEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание секторов.
        /// </summary>
        public static string JointAnalysis_SectorsDescription {
            get {
                return ResourceManager.GetString("JointAnalysis.SectorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод Хи-квадрат (Chi-Square Attack).
        /// </summary>
        public static string Methods_ChiSqrMethod {
            get {
                return ResourceManager.GetString("Methods.ChiSqrMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Методика комплексного стегоанализа.
        /// </summary>
        public static string Methods_ComplexMethod {
            get {
                return ResourceManager.GetString("Methods.ComplexMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценка на основе обученного бинарного классификатора для набора признаков: оценка CSA, RS, CKZhA, оценки качества, количество пикселей.
        /// </summary>
        public static string Methods_ComplexMethodTipText {
            get {
                return ResourceManager.GetString("Methods.ComplexMethodTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод Fast Additive Noise (HCF-COM).
        /// </summary>
        public static string Methods_FanMethod {
            get {
                return ResourceManager.GetString("Methods.FanMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Методика формирования вывода при совместном применении методов CSA и RS.
        /// </summary>
        public static string Methods_JointDecisionMethod {
            get {
                return ResourceManager.GetString("Methods.JointDecisionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стегоанализ последовательного Коха-Жао.
        /// </summary>
        public static string Methods_KzhaMethod {
            get {
                return ResourceManager.GetString("Methods.KzhaMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод Regular-Singular.
        /// </summary>
        public static string Methods_RsMethod {
            get {
                return ResourceManager.GetString("Methods.RsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод Sample Pair Analysis.
        /// </summary>
        public static string Methods_SpaMethod {
            get {
                return ResourceManager.GetString("Methods.SpaMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистические характеристики изображения.
        /// </summary>
        public static string Methods_Stats {
            get {
                return ResourceManager.GetString("Methods.Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод анализа сжатия по Жилкину.
        /// </summary>
        public static string Methods_ZcaMethod {
            get {
                return ResourceManager.GetString("Methods.ZcaMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота блока.
        /// </summary>
        public static string Params_Blocks_Height {
            get {
                return ResourceManager.GetString("Params.Blocks.Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина блока.
        /// </summary>
        public static string Params_Blocks_Width {
            get {
                return ResourceManager.GetString("Params.Blocks.Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синий канал.
        /// </summary>
        public static string Params_Channels_Blue {
            get {
                return ResourceManager.GetString("Params.Channels.Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зелёный канал.
        /// </summary>
        public static string Params_Channels_Green {
            get {
                return ResourceManager.GetString("Params.Channels.Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Красный канал.
        /// </summary>
        public static string Params_Channels_Red {
            get {
                return ResourceManager.GetString("Params.Channels.Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор анализируемых каналов.
        /// </summary>
        public static string Params_ChannelsChoosing {
            get {
                return ResourceManager.GetString("Params.ChannelsChoosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не учитывать пары с нулевой&amp;#10;ожидаемой частотой.
        /// </summary>
        public static string Params_Csa_ExcludeZeroPairs {
            get {
                return ResourceManager.GetString("Params.Csa.ExcludeZeroPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порог pValue.
        /// </summary>
        public static string Params_Csa_PValueThreshold {
            get {
                return ResourceManager.GetString("Params.Csa.PValueThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры стегоанализа по критерию Хи-квадрат.
        /// </summary>
        public static string Params_Csa_Title {
            get {
                return ResourceManager.GetString("Params.Csa.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порог объединения категорий.
        /// </summary>
        public static string Params_Csa_UnifyingThreshold {
            get {
                return ResourceManager.GetString("Params.Csa.UnifyingThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать режим накопления.
        /// </summary>
        public static string Params_Csa_UsePreviousCnums {
            get {
                return ResourceManager.GetString("Params.Csa.UsePreviousCnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объединять низкочастотные категории.
        /// </summary>
        public static string Params_Csa_UseUnifiedCategories {
            get {
                return ResourceManager.GetString("Params.Csa.UseUnifiedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Визуализировать область скрытой&amp;#10;информации.
        /// </summary>
        public static string Params_Csa_Visualize {
            get {
                return ResourceManager.GetString("Params.Csa.Visualize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порог дистанции Махаланобиса центра масс (COM).
        /// </summary>
        public static string Params_Fan_ComThreshold {
            get {
                return ResourceManager.GetString("Params.Fan.ComThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры стегоанализа метода Fast Additive Noise (HCF-COM).
        /// </summary>
        public static string Params_Fan_Title {
            get {
                return ResourceManager.GetString("Params.Fan.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически извлекать информацию.
        /// </summary>
        public static string Params_Kzha_AutoExtract {
            get {
                return ResourceManager.GetString("Params.Kzha.AutoExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступные коэффициенты.
        /// </summary>
        public static string Params_Kzha_AvailableCoeffs {
            get {
                return ResourceManager.GetString("Params.Kzha.AvailableCoeffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порог подозрительных значений.
        /// </summary>
        public static string Params_Kzha_CutThreshold {
            get {
                return ResourceManager.GetString("Params.Kzha.CutThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальный учитываемый&amp;#10;порог скрытия.
        /// </summary>
        public static string Params_Kzha_MinThreshold {
            get {
                return ResourceManager.GetString("Params.Kzha.MinThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранные коэффициенты.
        /// </summary>
        public static string Params_Kzha_SelectedCoeffs {
            get {
                return ResourceManager.GetString("Params.Kzha.SelectedCoeffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры стегоанализа метода Коха-Жао.
        /// </summary>
        public static string Params_Kzha_Title {
            get {
                return ResourceManager.GetString("Params.Kzha.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маска флиппинга.
        /// </summary>
        public static string Params_Rs_FlippingMask {
            get {
                return ResourceManager.GetString("Params.Rs.FlippingMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры стегоанализа методом Regular-Singular.
        /// </summary>
        public static string Params_Rs_Title {
            get {
                return ResourceManager.GetString("Params.Rs.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диагональное.
        /// </summary>
        public static string Params_Spa_Direction_Diagonal {
            get {
                return ResourceManager.GetString("Params.Spa.Direction.Diagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Горизонтальное.
        /// </summary>
        public static string Params_Spa_Direction_Horizontal {
            get {
                return ResourceManager.GetString("Params.Spa.Direction.Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор направления анализа.
        /// </summary>
        public static string Params_Spa_Direction_Title {
            get {
                return ResourceManager.GetString("Params.Spa.Direction.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вертикальное.
        /// </summary>
        public static string Params_Spa_Direction_Vertical {
            get {
                return ResourceManager.GetString("Params.Spa.Direction.Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры стегоанализа методом Sample Pair Analysis.
        /// </summary>
        public static string Params_Spa_Title {
            get {
                return ResourceManager.GetString("Params.Spa.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать двойной проход.
        /// </summary>
        public static string Params_Spa_UseDoubleDirection {
            get {
                return ResourceManager.GetString("Params.Spa.UseDoubleDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Горизонтальный.
        /// </summary>
        public static string Params_TraverseType_Horizontal {
            get {
                return ResourceManager.GetString("Params.TraverseType.Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор обхода массива пикселей.
        /// </summary>
        public static string Params_TraverseType_Title {
            get {
                return ResourceManager.GetString("Params.TraverseType.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вертикальный.
        /// </summary>
        public static string Params_TraverseType_Vertical {
            get {
                return ResourceManager.GetString("Params.TraverseType.Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BZIP2.
        /// </summary>
        public static string Params_Zca_CompressMethod_Bzip2 {
            get {
                return ResourceManager.GetString("Params.Zca.CompressMethod.Bzip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GZIP.
        /// </summary>
        public static string Params_Zca_CompressMethod_Gzip {
            get {
                return ResourceManager.GetString("Params.Zca.CompressMethod.Gzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор метода сжатия.
        /// </summary>
        public static string Params_Zca_CompressMethod_Title {
            get {
                return ResourceManager.GetString("Params.Zca.CompressMethod.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ZIP.
        /// </summary>
        public static string Params_Zca_CompressMethod_Zip {
            get {
                return ResourceManager.GetString("Params.Zca.CompressMethod.Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анализировать целиком (по всем каналам вместе).
        /// </summary>
        public static string Params_Zca_OverallCompression {
            get {
                return ResourceManager.GetString("Params.Zca.OverallCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порог коэффициента сжатия.
        /// </summary>
        public static string Params_Zca_RatioThreshold {
            get {
                return ResourceManager.GetString("Params.Zca.RatioThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры метода анализа сжатия по Жилкину.
        /// </summary>
        public static string Params_Zca_Title {
            get {
                return ResourceManager.GetString("Params.Zca.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string SettingsTab_Language {
            get {
                return ResourceManager.GetString("SettingsTab.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логирование.
        /// </summary>
        public static string SettingsTab_Logging {
            get {
                return ResourceManager.GetString("SettingsTab.Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень размытости.
        /// </summary>
        public static string Stats_Blur {
            get {
                return ResourceManager.GetString("Stats.Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень контраста.
        /// </summary>
        public static string Stats_Contrast {
            get {
                return ResourceManager.GetString("Stats.Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энтропия Хаварда-Чарвата.
        /// </summary>
        public static string Stats_Entropy_Havard {
            get {
                return ResourceManager.GetString("Stats.Entropy.Havard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энтропия Реньи.
        /// </summary>
        public static string Stats_Entropy_Renyi {
            get {
                return ResourceManager.GetString("Stats.Entropy.Renyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энтропия Шеннона.
        /// </summary>
        public static string Stats_Entropy_Shennon {
            get {
                return ResourceManager.GetString("Stats.Entropy.Shennon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энтропия Цаллиса.
        /// </summary>
        public static string Stats_Entropy_Tsallis {
            get {
                return ResourceManager.GetString("Stats.Entropy.Tsallis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энтропия Вайда.
        /// </summary>
        public static string Stats_Entropy_Vaida {
            get {
                return ResourceManager.GetString("Stats.Entropy.Vaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень шума.
        /// </summary>
        public static string Stats_Noise {
            get {
                return ResourceManager.GetString("Stats.Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень резкости.
        /// </summary>
        public static string Stats_Sharpness {
            get {
                return ResourceManager.GetString("Stats.Sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стегоанализатор.
        /// </summary>
        public static string Tabs_Analyzer {
            get {
                return ResourceManager.GetString("Tabs.Analyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стеганодекодер.
        /// </summary>
        public static string Tabs_Extractor {
            get {
                return ResourceManager.GetString("Tabs.Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стеганокодер.
        /// </summary>
        public static string Tabs_Hider {
            get {
                return ResourceManager.GetString("Tabs.Hider", resourceCulture);
            }
        }
    }
}
