// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace StegoRevealer_StegoCore_TrainingModule
{
    public partial class DecisionModel_ComplexSa_WithSpaFan2
    {
        /// <summary>
        /// model input class for DecisionModel_ComplexSa_WithSpaFan2.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ChiSqrHorizontalRelativeVolume")]
            public float ChiSqrHorizontalRelativeVolume { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"ChiSqrVerticalRelativeVolume")]
            public float ChiSqrVerticalRelativeVolume { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"RsRelativeVolume")]
            public float RsRelativeVolume { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"KzhaHorizontalThreshold")]
            public float KzhaHorizontalThreshold { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"KzhaHorizontalBitsVolume")]
            public float KzhaHorizontalBitsVolume { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"KzhaHorizontalRelativeVolume")]
            public float KzhaHorizontalRelativeVolume { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"KzhaVerticalThreshold")]
            public float KzhaVerticalThreshold { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"KzhaVerticalBitsVolume")]
            public float KzhaVerticalBitsVolume { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"KzhaVerticalRelativeVolume")]
            public float KzhaVerticalRelativeVolume { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Noise")]
            public float Noise { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Sharpness")]
            public float Sharpness { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"Blur")]
            public float Blur { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Contrast")]
            public float Contrast { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"EntropyShennon")]
            public float EntropyShennon { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"EntropyRenyi25")]
            public float EntropyRenyi25 { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"EntropyRenyi11")]
            public float EntropyRenyi11 { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"EntropyRenyi05")]
            public float EntropyRenyi05 { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"EntropyHavard")]
            public float EntropyHavard { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"EntropyTsallis")]
            public float EntropyTsallis { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"EntropyVaida")]
            public float EntropyVaida { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"Width")]
            public float Width { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"Height")]
            public float Height { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"PixelsNum")]
            public float PixelsNum { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"SpaMessageRelativeVolume")]
            public float SpaMessageRelativeVolume { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"FanMahalanobisDistance")]
            public float FanMahalanobisDistance { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"IsDataHided")]
            public bool IsDataHided { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DecisionModel_ComplexSa_WithSpaFan2.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ChiSqrHorizontalRelativeVolume")]
            public float ChiSqrHorizontalRelativeVolume { get; set; }

            [ColumnName(@"ChiSqrVerticalRelativeVolume")]
            public float ChiSqrVerticalRelativeVolume { get; set; }

            [ColumnName(@"RsRelativeVolume")]
            public float RsRelativeVolume { get; set; }

            [ColumnName(@"KzhaHorizontalThreshold")]
            public float KzhaHorizontalThreshold { get; set; }

            [ColumnName(@"KzhaHorizontalBitsVolume")]
            public float KzhaHorizontalBitsVolume { get; set; }

            [ColumnName(@"KzhaHorizontalRelativeVolume")]
            public float KzhaHorizontalRelativeVolume { get; set; }

            [ColumnName(@"KzhaVerticalThreshold")]
            public float KzhaVerticalThreshold { get; set; }

            [ColumnName(@"KzhaVerticalBitsVolume")]
            public float KzhaVerticalBitsVolume { get; set; }

            [ColumnName(@"KzhaVerticalRelativeVolume")]
            public float KzhaVerticalRelativeVolume { get; set; }

            [ColumnName(@"Noise")]
            public float Noise { get; set; }

            [ColumnName(@"Sharpness")]
            public float Sharpness { get; set; }

            [ColumnName(@"Blur")]
            public float Blur { get; set; }

            [ColumnName(@"Contrast")]
            public float Contrast { get; set; }

            [ColumnName(@"EntropyShennon")]
            public float EntropyShennon { get; set; }

            [ColumnName(@"EntropyRenyi25")]
            public float EntropyRenyi25 { get; set; }

            [ColumnName(@"EntropyRenyi11")]
            public float EntropyRenyi11 { get; set; }

            [ColumnName(@"EntropyRenyi05")]
            public float EntropyRenyi05 { get; set; }

            [ColumnName(@"EntropyHavard")]
            public float EntropyHavard { get; set; }

            [ColumnName(@"EntropyTsallis")]
            public float EntropyTsallis { get; set; }

            [ColumnName(@"EntropyVaida")]
            public float EntropyVaida { get; set; }

            [ColumnName(@"Width")]
            public float Width { get; set; }

            [ColumnName(@"Height")]
            public float Height { get; set; }

            [ColumnName(@"PixelsNum")]
            public float PixelsNum { get; set; }

            [ColumnName(@"SpaMessageRelativeVolume")]
            public float SpaMessageRelativeVolume { get; set; }

            [ColumnName(@"FanMahalanobisDistance")]
            public float FanMahalanobisDistance { get; set; }

            [ColumnName(@"IsDataHided")]
            public bool IsDataHided { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; } = [];

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("DecisionModel_ComplexSa_WithSpaFan2.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
