<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishSingleFile>true</PublishSingleFile>
		<DebugType>embedded</DebugType>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CsvHelper" />
		<PackageReference Include="Microsoft.ML" />
		<PackageReference Include="Microsoft.ML.FastTree" />
		<PackageReference Include="Microsoft.ML.LightGbm" />
		<PackageReference Include="Plotly.NET" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux" />
		<PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" />
		<PackageReference Include="SkiaSharp.NativeAssets.Win32" />
		<PackageReference Include="SkiaSharp.NativeAssets.macOS" />
	</ItemGroup>
	<!--<ItemGroup>
    <ProjectReference Include="..\StegoRevealer.StegoCore\StegoRevealer.StegoCore.csproj" />
  </ItemGroup>-->
	<ItemGroup Label="DecisionModel">
		<None Include="DecisionModel.mlnet">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\StegoRevealer.StegoCore\StegoRevealer.StegoCore.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="TrainingData\" />
		<Folder Include="TestData\" />
	</ItemGroup>
	<ItemGroup Label="DecisionModel_ComplexSa">
		<None Include="DecisionModel_ComplexSa.mlnet">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Label="DecisionModel_ComplexSaNoQuality">
		<None Include="DecisionModel_ComplexSaNoQuality.mlnet">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Label="DecisionModel_ComplexSaNoVertical">
		<None Include="DecisionModel_ComplexSaNoVertical.mlnet">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Label="DecisionModel_ComplexSaNoPixelsNum">
		<None Include="DecisionModel_ComplexSaNoPixelsNum.mlnet">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Label="DecisionModel_ComplexSaOnlySaMethods">
		<None Include="DecisionModel_ComplexSaOnlySaMethods.mlnet">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<None Update="TestData\MlAnalysisDataTesting.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestData\MlAnalysisDataTesting2Lsb_ForComplexSa.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestData\MlAnalysisDataTesting_ForComplexSa.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestData\MlAnalysisDataTesting_ForComplexSaNoKzha.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestData\MlAnalysisDataTesting_ForComplexSaNoPixelsNum.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestData\MlAnalysisDataTesting_ForComplexSaNoQuality.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestData\MlAnalysisDataTesting_ForComplexSaNoVertical.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestData\MlAnalysisDataTesting_ForComplexSaOnlySaMethods.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TrainingData\MlAnalysisData_ComplexSa.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TrainingData\MlAnalysisData_ComplexSaNoKzha.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TrainingData\MlAnalysisData_ComplexSaNoPixelsNum.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TrainingData\MlAnalysisData_ComplexSaNoQuality.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TrainingData\MlAnalysisData_ComplexSaNoVertical.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TrainingData\MlAnalysisData_ComplexSaOnlySaMethods.csv">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Label="DecisionModel_ComplexSaNoKzha">
		<None Include="DecisionModel_ComplexSaNoKzha.mlnet">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Label="DecisionModel_ComplexSa_WithSpaFan2">
		<None Include="DecisionModel_ComplexSa_WithSpaFan2.mlnet">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>