// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace StegoRevealer_StegoCore_TrainingModule
{
    public partial class StegoModelTest1
    {
        public const string RetrainFilePath =  @"D:\Temp\_DataSets\.Samples\Sample1_50PercentClear_data_NEW.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"ChiSquareVolume", @"ChiSquareVolume"),new InputOutputColumnPair(@"RsVolume", @"RsVolume"),new InputOutputColumnPair(@"KzhaThreshold", @"KzhaThreshold"),new InputOutputColumnPair(@"KzhaMessageVolume", @"KzhaMessageVolume"),new InputOutputColumnPair(@"ChiSquareVolume_Vertical", @"ChiSquareVolume_Vertical"),new InputOutputColumnPair(@"KzhaThreshold_Vertical", @"KzhaThreshold_Vertical"),new InputOutputColumnPair(@"KzhaMessageVolume_Vertical", @"KzhaMessageVolume_Vertical"),new InputOutputColumnPair(@"NoiseValue", @"NoiseValue"),new InputOutputColumnPair(@"SharpnessValue", @"SharpnessValue"),new InputOutputColumnPair(@"BlurValue", @"BlurValue"),new InputOutputColumnPair(@"ContrastValue", @"ContrastValue"),new InputOutputColumnPair(@"EntropyShennonValue", @"EntropyShennonValue"),new InputOutputColumnPair(@"EntropyRenyiValue", @"EntropyRenyiValue")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"ChiSquareVolume",@"RsVolume",@"KzhaThreshold",@"KzhaMessageVolume",@"ChiSquareVolume_Vertical",@"KzhaThreshold_Vertical",@"KzhaMessageVolume_Vertical",@"NoiseValue",@"SharpnessValue",@"BlurValue",@"ContrastValue",@"EntropyShennonValue",@"EntropyRenyiValue"}))      
                                    .Append(mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=16,MinimumExampleCountPerLeaf=9,NumberOfTrees=86,MaximumBinCountPerFeature=39,FeatureFraction=0.990015524757507,LearningRate=0.0978144404155983,LabelColumnName=@"DataWasHided",FeatureColumnName=@"Features",DiskTranspose=false}));

            return pipeline;
        }
    }
 }
