// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
namespace StegoRevealer_StegoCore_TrainingModule
{
    public partial class DecisionModel
    {
        /// <summary>
        /// model input class for DecisionModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ChiSquareVolume")]
            public float ChiSquareVolume { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"RsVolume")]
            public float RsVolume { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"KzhaThreshold")]
            public float KzhaThreshold { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"KzhaMessageVolume")]
            public float KzhaMessageVolume { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"NoiseValue")]
            public float NoiseValue { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"SharpnessValue")]
            public float SharpnessValue { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"BlurValue")]
            public float BlurValue { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"ContrastValue")]
            public float ContrastValue { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"EntropyShennonValue")]
            public float EntropyShennonValue { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"EntropyRenyiValue")]
            public float EntropyRenyiValue { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"DataWasHided")]
            public bool DataWasHided { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DecisionModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ChiSquareVolume")]
            public float ChiSquareVolume { get; set; }

            [ColumnName(@"RsVolume")]
            public float RsVolume { get; set; }

            [ColumnName(@"KzhaThreshold")]
            public float KzhaThreshold { get; set; }

            [ColumnName(@"KzhaMessageVolume")]
            public float KzhaMessageVolume { get; set; }

            [ColumnName(@"NoiseValue")]
            public float NoiseValue { get; set; }

            [ColumnName(@"SharpnessValue")]
            public float SharpnessValue { get; set; }

            [ColumnName(@"BlurValue")]
            public float BlurValue { get; set; }

            [ColumnName(@"ContrastValue")]
            public float ContrastValue { get; set; }

            [ColumnName(@"EntropyShennonValue")]
            public float EntropyShennonValue { get; set; }

            [ColumnName(@"EntropyRenyiValue")]
            public float EntropyRenyiValue { get; set; }

            [ColumnName(@"DataWasHided")]
            public bool DataWasHided { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("DecisionModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();

            string resourceName = "StegoRevealer.StegoCore.DecisionModule.DecisionModel.mlnet";
            var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName);
            ITransformer mlModel = mlContext.Model.Load(stream, out _);
            stream?.Close();

            //ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
