<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>

		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PublishSingleFile>true</PublishSingleFile>
		<DebugType>embedded</DebugType>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="DecisionModel_ComplexSa.training.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="DecisionModel_ComplexSa.mlnet" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="DecisionModel_ComplexSa.mlnet" />
		<EmbeddedResource Include="DecisionModel_ComplexSa.training.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ML" />
		<PackageReference Include="Microsoft.ML.FastTree" />
		<PackageReference Include="Microsoft.ML.LightGbm" />
		<PackageReference Include="Plotly.NET" />
	</ItemGroup>
	<!--<ItemGroup>
		<ProjectReference Include="..\StegoRevealer.StegoCore.TrainingModule\StegoRevealer.StegoCore.TrainingModule.csproj" />
	</ItemGroup>-->

</Project>
